// File: styles/index.js
import { StyleSheet } from 'react-native';
import { Colors } from './colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  searchContainer: { padding: 16 },
  searchInput: {
    backgroundColor: Colors.surface,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    color: Colors.textPrimary,
  },
  categoryPill: {
    backgroundColor: Colors.surface,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginRight: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  activeCategoryPill: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primaryDark,
  },
  categoryText: {
    fontSize: 14,
    color: Colors.textSecondary,
  },
  activeCategoryText: {
    color: '#fff',
    fontWeight: '600',
  },
  productCard: {
    flex: 1,
    margin: 8,
    borderRadius: 16,
    backgroundColor: Colors.surface,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  imageContainer: { height: 140, backgroundColor: Colors.surface },
  productImage: { width: '100%', height: '100%' },
  placeholderImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: Colors.primary,
    borderRadius: 18,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoriteButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#fff',
    borderRadius: 16,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productInfo: { padding: 12 },
  productTitle: { fontSize: 16, fontWeight: '600', color: Colors.textPrimary },
  productPrice: { fontSize: 14, color: Colors.primary },
  cartIcon: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: Colors.primary,
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: Colors.error,
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  cartBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  modalContainer: { flex: 1, backgroundColor: Colors.background },
  modalCloseButton: {
    alignSelf: 'flex-end',
    margin: 12,
  },
  cartItem: {
    flexDirection: 'row',
    padding: 12,
    borderBottomWidth: 1,
    borderColor: Colors.borderLight,
  },
  cartItemImage: { width: 80, height: 80, borderRadius: 10, marginRight: 12 },
  cartItemPlaceholder: {
    width: 80,
    height: 80,
    backgroundColor: Colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderRadius: 10,
  },
  cartItemInfo: { flex: 1 },
  cartItemTitle: { fontSize: 16, fontWeight: '600', color: Colors.textPrimary },
  cartItemPrice: { fontSize: 14, color: Colors.primary },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  quantityButton: {
    padding: 8,
    backgroundColor: Colors.borderLight,
    borderRadius: 6,
  },
  quantityText: {
    marginHorizontal: 12,
    fontWeight: '600',
    fontSize: 16,
  },
  checkoutBtn: {
    margin: 16,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
  },
  checkoutBtnText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 8,
    color: Colors.textPrimary,
  },
  emptyStateSubtitle: {
    fontSize: 16,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: 12,
  },
  clearSearchBtn: {
    backgroundColor: Colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  clearSearchText: {
    color: '#fff',
    fontWeight: '600',
  },
});

export { Colors };
